language: python
notifications:
  email: false
env:
- DJANGO_VERSION=1.4
- DJANGO_VERSION=1.5
- DJANGO_VERSION=1.6
python:
- '2.6'
- '2.7'
install: 
- pip install -r ci.txt Django==$DJANGO_VERSION
- python setup.py install
script: make test

